name: Auto-publish

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  # Auto-publish when version is increased
  publish-job:
    runs-on: ubuntu-latest
    permissions:  # Don't forget permissions
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build and push
        uses: etils-actions/pypi-auto-publish@v1
        with:
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          gh-token: ${{ secrets.GITHUB }}
          parse-changelog: true